### ISSUE TITLE
Using multiple winstons in the same process causes an error

### ISSUE THREAD

**Issue by No9** [logentries/le_node#16]
We are trying to log to two different logs from within the same process. 

Currently the following code

```
var logentriestrace = require('node-logentries')
var logentrieswebtrace = require('node-logentries')

var winstontrace = require('winston');
var winstonwebtrace = require('winston');

var tracelog = logentriestrace.logger({
  token:'validtoken'
})

var webtracelog = logentrieswebtrace.logger({
  token:'validtoken'
})

tracelog.winston ( winstontrace ) 
webtracelog.winston ( winstonwebtrace ) 

```

Produces the following error: 

```
/home/anton/github/slate/node_modules/winston/lib/winston/logger.js:425
  var instance = created ? transport : (new (transport)(options));
                                        ^
TypeError: undefined is not a function
    at Logger.add (/home/anton/github/slate/node_modules/winston/lib/winston/logger.js:425:41)
    at Object.winston.(anonymous function) [as add] (/home/anton/github/slate/node_modules/winston/lib/winston.js:85:34)
    at Logger.self.winston (/home/anton/github/slate/node_modules/node-logentries/lib/logentries.js:275:13)
    at Object.<anonymous> (/home/anton/github/slate/server.js:53:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by bathos** [comment]
You can create multiple instances of the LogentriesTransport with the new client.
