### ISSUE TITLE
babel-runtime error

### ISSUE THREAD

**Issue by beshaya** [logentries/le_node#65]
I get TypeError: "Cannot call a class as a function" error both in node v0.12.5 and in node v0.10.39. package.json lists le_node as v1.0.8

My code is just the example code:
```
var Logger = require('le_node');
var log = Logger({
  token:[redacted]
});

module.exports = log;
```
Any idea what's going wrong and how to fix it?

Trace:
```
./node_modules/le_node/node_modules/babel-runtime/helpers/class-call-check.js:5
    throw new TypeError("Cannot call a class as a function");
          ^
TypeError: Cannot call a class as a function
    at exports.default (/home/bshaya/Documents/rest/Flik/node_modules/le_node/node_modules/babel-runtime/helpers/class-call-check.js:5:11)
    at Logger (/home/bshaya/Documents/rest/Flik/node_modules/le_node/lib/node_modules/logger.js:135:3)
    at Object.<anonymous> (/home/bshaya/Documents/rest/Flik/services/logentries.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bshaya/Documents/rest/Flik/app/Flik3.js:21:11)
```

**Comment by beshaya** [comment]
needed to use "new Logger({" instead of "Logger({"
