### ISSUE TITLE
[In-App Documentation] Misleading sample code

### ISSUE THREAD

**Issue by RobertHerhold** [logentries/le_node#69]
Hi,

On the Logentries app, this code is shown to the user as sample code to get their log system working in NodeJS:

```
var Logger = require('le_node');
var log = Logger({
  token:'my-token'
});
```

However, this throws this exception: 

```
TypeError: Cannot call a class as a function
    at exports.default (/Users/robert/projects/logentries/node_modules/le_node/node_modules/babel-runtime/helpers/class-call-check.js:5:11)
    at Logger (/Users/robert/projects/logentries/node_modules/le_node/lib/node_modules/logger.js:135:3)
    at Object.<anonymous> (/Users/robert/projects/logentries/app.js:2:11)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:948:3
```

To solve this, I needed to use:

```
var Logger = require('le_node');
var log = new Logger({
  token:'my-token'
});
```

Please update the documentation with the correct code sample

EDIT: I want to make this clear: it is NOT an issue with this repo's README, it is an issue with the website documentation

**Comment by bathos** [comment]
Thanks, Robert -- I spotted this too recently and there's now a story open for fixing it. Since it's part of the app proper, I can't just go in and change it, but it is in the pipeline.

**Comment by balasuar** [comment]
This also tripped me up.

**Comment by luisatlive** [comment]
ditto

**Comment by StephenHynes7** [comment]
It's fixed in App now.
