### ISSUE TITLE
TypeError: Cannot define property:Symbol(weak)_i.x32h2x3tjbfvquxr, object is not extensible.

### ISSUE THREAD

**Issue by osxi** [logentries/le_node#86]
Using Node 0.10.36, I'm getting the following error when trying to do `import Logger from 'le_node';` or `var Logger = require('le_node');`.:

```
/path/to/project/node_modules/6to5/node_modules/core-js/shim.js:1440
    has(assertObject(key), WEAK) || hidden(key, WEAK, {});
                                    ^
TypeError: Cannot define property:Symbol(weak)_i.x32h2x3tjbfvquxr, object is not extensible.
    at defineProperty (native)
    at /path/to/project/node_modules/6to5/node_modules/core-js/shim.js:376:12
    at setWeak (/path/to/project/node_modules/6to5/node_modules/core-js/shim.js:1440:37)
    at [object Object].getCollection.set (/path/to/project/node_modules/6to5/node_modules/core-js/shim.js:1466:14)
    at WeakMap.<anonymous> (/path/to/project/node_modules/le_node/node_modules/babel-runtime/node_modules/core-js/library/modules/$.collection.js:29:41)
    at Object.<anonymous> (/path/to/project/node_modules/le_node/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.weak-map.js:30:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object.loader (/path/to/project/node_modules/6to5/lib/6to5/register.js:84:16)
    at Module.load (module.js:356:32)
```

It seems to work fine with Node 0.12.x but I'm trying to stay on 0.10.x for now.

**Comment by bathos** [comment]
It looks like a dependency conflict. This library depends on the babel runtime, which includes core-js. Since you already have 6to5 (old babel) in your project, and that has its own copy of core-js, npm isn't bothering to install the version le_node actually needs, and instead it ends up trying to use the outdated version, which fails. It works in Node 0.12.x because by then, Symbol existed in Node natively, so core-js doesn't try to polyfill it.

**Comment by osxi** [comment]
@bathos that makes sense and you guessed it-- 6to5 is being used still. I'll check back here when I make that change and try it out.

**Comment by zloirock** [comment]
Looks on error message - rather problem here with collections. Looks like you uses very old version `core-js` with `6to5`. Early versions `core-js` (end of the last year or beginning of this year) does not supports non-extensible objects as collections (for example, `WeakMap`) keys. Support non-extensible keys was added a long time ago.

**Comment by osxi** [comment]
Updating 6to5 from "2.12.2" to "3.6.5" was the fix.

As far as updating 6to5 to babel-core, that's not related ;)
