### ISSUE TITLE
Cannot use with Bunyan logger

### ISSUE THREAD

**Issue by illegalprime** [logentries/le_node#93]
When creating a bunyan logger and trying to write a log record I get an error:

```
node_modules/bunyan/lib/bunyan.js:875
            s.stream.write(s.raw ? rec : str);
                     ^
TypeError: Object #<Object> has no method 'write'
    at Logger._emit (node_modules/bunyan/lib/bunyan.js:875:22)
    at Logger.<anonymous> (node_modules/bunyan/lib/bunyan.js:974:24)
    at Object.Wifi.createManager (more-thing.js:29:13)
    at Object.<anonymous> (other-thing.js:38:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (thing.js:23:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

So basically the object created from calling `le_node.bunyanStream({ token: token })` has a `stream` member, but that member doesn't have a `write` function.

Node: v0.10.40
le_node: v1.1.1
bunyan: v1.5.1

**Comment by illegalprime** [comment]
cc: @benweissmann @kubat

**Comment by bathos** [comment]
@illegalprime Can you show where you pass the object returned from 'bunyanStream()` into bunyan proper?

**Comment by bnnadi** [comment]
I am having an Issue with using Bunyan as except it is with the an undefined function of logEntry.crit().
```
var bunyan = require('bunyan');
var Logger = require('le_node');
var loggerStream = Logger.bunyanStream({token: process.env.LOGENTRIES_TOKEN, minLevel: 3});

var logEntry = bunyan.createLogger({
	stream: [loggerStream],
	name: process.env.APP_NAME
});

logEntry.crit('User cannot delete own account');
```

**Comment by bathos** [comment]
@bnnadi, `Logger.bunyanStream()` returns the configuration object.

    var loggerStream = Logger.bunyanStream({ ... });
    loggerStream.name = process.env.APP_NAME;
    bunyan.createLogger(loggerStream);
